"use client";
import Link from "next/link";
import { ArrowUpRightIcon, ClockIcon, MagnifyingGlassIcon, XIcon } from "@phosphor-icons/react";
import { useMemo, useState } from "react";
import type { LogMeta } from "../data/logs";
import { TechBadge } from "./SiteShell";
import { AnimatedFilterSelect } from "./AnimatedFilterSelect";
function highlight(value: string, query: string) { if (!query.trim()) return value; const parts = value.split(new RegExp(`(${query.replace(/[.*+?^${}()|[\\]\\]/g, "\\$&")})`, "ig")); return parts.map((part, index) => part.toLowerCase() === query.toLowerCase() ? <mark key={`${part}-${index}`}>{part}</mark> : part); }
export function LogsExplorer({ logs }: { logs: LogMeta[] }) {
  const [query, setQuery] = useState(""); const [tag, setTag] = useState("全部标签"); const [year, setYear] = useState("全部年份"); const tags = useMemo(() => ["全部标签", ...Array.from(new Set(logs.flatMap(log => log.tags)))], [logs]); const years = useMemo(() => ["全部年份", ...Array.from(new Set(logs.map(log => log.date.slice(0, 4))))], [logs]); const filtered = useMemo(() => logs.filter(log => { const text = `${log.title} ${log.summary} ${log.tags.join(" ")} ${log.content}`.toLowerCase(); return (!query || text.includes(query.toLowerCase())) && (tag === "全部标签" || log.tags.includes(tag)) && (year === "全部年份" || log.date.startsWith(year)); }), [logs, query, tag, year]);
  return <div className="logs-explorer" id="logs-content"><div className="logs-toolbar" id="log-search"><label className="search-field"><MagnifyingGlassIcon size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索标题、标签、摘要或正文" aria-label="搜索日志" />{query && <button type="button" aria-label="清除搜索" onClick={() => setQuery("")}><XIcon size={15} /></button>}</label><AnimatedFilterSelect label="标签" value={tag} options={tags} onChange={setTag} /><AnimatedFilterSelect label="年份" value={year} options={years} onChange={setYear} /><span className="filter-status">Published · {filtered.length}</span></div><div className="logs-results"><p className="results-count">{query || tag !== "全部标签" || year !== "全部年份" ? `匹配 ${filtered.length} 条日志` : "按日期倒序"}</p>{filtered.length ? filtered.map(log => <article className="dense-log-row" key={log.slug}><div className="dense-log-date"><time dateTime={log.date}>{log.date}</time><span><ClockIcon size={13} />{log.readingTime}</span></div><Link href={`/logs/${log.slug}`} className="dense-log-main"><h2>{highlight(log.title, query)}</h2><p>{highlight(log.summary, query)}</p><div className="log-tags">{log.tags.map(item => <TechBadge key={item}>{highlight(item, query)}</TechBadge>)}</div></Link><Link href={`/logs/${log.slug}`} className="dense-log-arrow" aria-label={`阅读 ${log.title}`}><ArrowUpRightIcon size={19} /></Link></article>) : <div className="empty-state">没有匹配的日志。尝试更换关键词或筛选条件。</div>}</div></div>;
}
