import Link from "next/link";
import { Container, SectionHeading, StatusBadge } from "./components/SiteShell";
import { ProjectCard } from "./components/ProjectCard";
import { LogCard } from "./components/LogCard";
import { projects } from "./data/projects";
import { logs } from "./data/logs";

export default function Home() { return <>
  <section className="relative min-h-[720px] overflow-hidden border-b border-white/10"><div className="absolute inset-0 bg-[url('/media/aurora-australis.jpg')] bg-cover bg-center opacity-35" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_25%,rgba(255,141,77,.22),transparent_30%),linear-gradient(180deg,rgba(11,11,13,.35),#0b0b0d_92%)]" /><div className="absolute -right-24 top-28 h-80 w-80 rounded-full bg-[var(--accent)]/15 blur-3xl aurora-orb" /><div className="absolute left-[-10%] top-52 h-64 w-64 rounded-full bg-blue-400/10 blur-3xl aurora-orb" /><Container className="relative flex min-h-[720px] flex-col justify-center pb-16 pt-36"><div className="max-w-4xl reveal"><div className="mb-7 flex flex-wrap items-center gap-3"><span className="eyebrow">个人开发门户 / 2026</span><StatusBadge status="active" /><span className="text-xs text-white/45">VPS · AI · Automation</span></div><h1 className="display max-w-4xl text-6xl leading-[.88] text-white md:text-8xl">把想法变成<br /><span className="text-[var(--accent-soft)]">可运行的系统。</span></h1><p className="mt-7 max-w-2xl text-base leading-7 text-white/65 md:text-lg">我是 Flower ZC，持续构建 AI agent、开发基础设施与自动化系统。这里记录正在运行的项目、真实的部署过程，以及下一步要解决的问题。</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/projects" className="rounded-full bg-white px-5 py-3 text-sm font-semibold text-black transition hover:bg-[var(--accent-soft)]">浏览项目 <span className="ml-3">↗</span></Link><Link href="/logs" className="glass rounded-full px-5 py-3 text-sm text-white/80 transition hover:text-white">阅读开发日志 <span className="ml-3">→</span></Link></div></div><div className="mt-auto grid gap-3 pt-20 sm:grid-cols-3"><div className="glass rounded-2xl p-4 reveal reveal-delay-1"><p className="text-xs text-dim">当前焦点</p><p className="mt-2 text-sm text-white/85">Hermes Agent + 个人基础设施</p></div><div className="glass rounded-2xl p-4 reveal reveal-delay-2"><p className="text-xs text-dim">服务器状态</p><p className="mt-2 flex items-center gap-2 text-sm text-white/85"><i className="pulse-dot h-2 w-2 rounded-full bg-emerald-300" />运行稳定 · Ubuntu 24.04</p></div><div className="glass rounded-2xl p-4 reveal reveal-delay-3"><p className="text-xs text-dim">下一阶段</p><p className="mt-2 text-sm text-white/85">模型接入 · Webhook · 备份</p></div></div></Container></section>
  <section className="py-24 md:py-32"><Container><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="正在运行" title="现在正在构建" description="不追求一次性做完，先让每个系统有清晰边界、可回放的证据和下一步。" /><Link href="/projects" className="mb-10 text-sm text-white/60 transition hover:text-white">查看全部项目 ↗</Link></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{projects.slice(0, 3).map(project => <ProjectCard key={project.slug} project={project} />)}</div></Container></section>
  <section className="border-y border-white/10 bg-white/[.015] py-24 md:py-32"><Container><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><SectionHeading eyebrow="最新记录" title="开发日志" description="保留命令、错误、根因和修复逻辑，让每一次部署都能被复盘。" /><Link href="/logs" className="mb-10 text-sm text-white/60 transition hover:text-white">进入日志 ↗</Link></div><div className="max-w-5xl">{logs.slice(0, 2).map(log => <LogCard key={log.slug} log={log} />)}</div></Container></section>
  <section className="relative overflow-hidden py-24 md:py-32"><div className="absolute right-0 top-0 h-72 w-72 rounded-full bg-[var(--accent)]/10 blur-3xl" /><Container className="relative"><div className="glass grid gap-8 rounded-[2rem] p-6 md:grid-cols-[1.2fr_.8fr] md:p-10"><div><p className="eyebrow mb-4">长期方向</p><h2 className="display max-w-2xl text-4xl text-white md:text-6xl">先把基础设施<br /><span className="text-[var(--accent-soft)]">变成生产力。</span></h2></div><div className="flex flex-col justify-between gap-8"><p className="text-sm leading-7 text-muted">从一台 VPS 出发，把 AI 服务、API、自动化、数据和部署连接起来。每个项目都服务于下一次更快、更可靠的构建。</p><Link href="/roadmap" className="text-sm text-white/75 hover:text-white">查看路线图 →</Link></div></div></Container></section>
</>; }
